Add TRSS parser
AdoptOpenJDK/openjdk-tests pull request #2190
Opened 2021-01-21 11:22 UTC by karianna

2021-01-22 03:11 UTC, smlambert reviewed
Minor typo, otherwise LGTM

2021-01-22 03:11 UTC, smlambert commented on doc/Triage.md
> +We've created a NodeJS module to parse TRSS output, convert it to Markdown so folks can paste that summary into a GitHuv issue.
Github versus Githuv

2021-01-23 14:25 UTC, smlambert requested changes
A minor typo, otherwise LGTM

2021-01-25 16:06 UTC, smlambert commented
Ping @karianna

2021-01-25 17:58 UTC, smlambert approved these changes
thanks @gdams and @karianna ...  I realize there are some other doc updates we should do in this file, but I'll create a separate PR.

2021-01-25 19:59 UTC, sophia-guo approved these changes
LGTM

2021-01-25 19:59 UTC, merged