Change default SDK to nightly in PR build
AdoptOpenJDK/openjdk-tests pull request #2202
Opened 2021-01-23 19:57 UTC by xfxcwynlc

Change from releases to nightly at line 36, 73.
Closes: #2187 
Signed-off-by: Yanan Wang <xfxcwynlc@gmail.com>

2021-01-23 20:43 UTC, sophia-guo commented
Is this duplicate or part of #2201 ?

2021-01-23 21:10 UTC, xfxcwynlc commented
> Is this duplicate or part of #2201 ?

I created a new pull request and only focused on changing 'releases' to 'nightly', while #2201 is trying to fix 2 issues at the same time, one for ready_to_review and the second for 'releases to nightly', but the later one forgot to change line 73.

2021-01-24 18:01 UTC, llxia approved these changes
LGTM

2021-01-24 18:19 UTC, sophia-guo requested changes

2021-01-24 18:19 UTC, sophia-guo commented on .github/workflows/PushOrPRtestbuild.yml
> +        source: 'nightly'  #nightly for nightly test builds
Might just remove the comment as it doesn't help much.

2021-01-24 18:19 UTC, sophia-guo commented on .github/workflows/PushOrPRtestbuild.yml
> +        source: 'nightly'  #nightly for nightly test builds
Same as comment above, just remove the comment.

2021-01-25 16:05 UTC, smlambert commented
@xfxcwynlc if you remove the unneeded comments as @sophia-guo requested then this PR will be ready to merge.

2021-01-25 19:05 UTC, sophia-guo approved these changes
LGTM

2021-01-25 19:05 UTC, merged